name: docker build

on : [push]

env:
   
#      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
       AWS_REGION: ap-south-1
       REPO_NAME: demogithub  
       AWS_ACCOUNT: "366140438193"

jobs:
  docker-build:
    runs-on: ubuntu-latest

  steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: print commit id
        run: echo "${{ env.GIT_SHA }}"


      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION  }} 

      - name: Login to Amazon ECR
        run: |
         # Retrieves the ECR login password and logs in to ECR
          aws ecr get-login-password --region ${{ env.AWS_REGION }} | docker login --username AWS --password-stdin ${{ env.AWS_ACCOUNT }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com
        # aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 366140438193.dkr.ecr.eu-north-1.amazonaws.com/demogithub

      - name: Build and Push Docker Image
        run: |
          # Builds the Docker image with the appropriate tag and pushes it to ECR
          docker build -t ${{ env.AWS_ACCOUNT }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.REPO_NAME }}:${{ env.GIT_SHA }} .
          docker push ${{ env.AWS_ACCOUNT }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.REPO_NAME }}:${{ env.GIT_SHA }}
 